//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carrier.Resources.lang_RU", typeof(lang_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе....
        /// </summary>
        internal static string about_name {
            get {
                return ResourceManager.GetString("about_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе Перевозчик.
        /// </summary>
        internal static string about_name_2 {
            get {
                return ResourceManager.GetString("about_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения нажмите ЛКМ.
        /// </summary>
        internal static string auto_help {
            get {
                return ResourceManager.GetString("auto_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авто.
        /// </summary>
        internal static string auto_name {
            get {
                return ResourceManager.GetString("auto_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В автоматическом режиме программа будет 
        ///сама выполнять алгоритм решения задачи о 
        ///Перевозчике. Пользователь может нажать ЛКМ 
        ///для продвижения решения задачи вперед или 
        ///нажать ПКМ для продвижения решения задачи 
        ///назад.
        ///
        ///
        ///.
        /// </summary>
        internal static string auto_text {
            get {
                return ResourceManager.GetString("auto_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевезти!.
        /// </summary>
        internal static string carrier {
            get {
                return ResourceManager.GetString("carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (C) Фатрахманов Никита 2025.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий кадр:.
        /// </summary>
        internal static string curr_frame {
            get {
                return ResourceManager.GetString("curr_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный код на Github!.
        /// </summary>
        internal static string github_link {
            get {
                return ResourceManager.GetString("github_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевозчик.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string lang_name {
            get {
                return ResourceManager.GetString("lang_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задача не решена!
        ///Были нарушены условия!
        ///
        ///Чтобы начать занаво нажите кнопку &quot;Заново&quot;.
        /// </summary>
        internal static string lose_text {
            get {
                return ResourceManager.GetString("lose_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ручной.
        /// </summary>
        internal static string manual_name {
            get {
                return ResourceManager.GetString("manual_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ручном режиме пользователю предстоит
        ///самому решить задачу о Перевозчике. 
        ///Пользователь должен придерживаться 
        ///определенных правил, иначе он 
        ///проиграет. В отличие от авто-режима, 
        ///пользователю для перемещения 
        ///объектов нужно нажать на них ЛКМ и нажать     
        ///на кнопку &quot;Перевезти&quot;..
        /// </summary>
        internal static string manual_text {
            get {
                return ResourceManager.GetString("manual_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание:.
        /// </summary>
        internal static string mode_desc_name {
            get {
                return ResourceManager.GetString("mode_desc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите режим:.
        /// </summary>
        internal static string mode_sel {
            get {
                return ResourceManager.GetString("mode_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заново.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string settings_name {
            get {
                return ResourceManager.GetString("settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия: нужно перевезти человека, козу, волка и капусту на другой берег; в лодке помещаются только двое;
        ///лодка может плыть только с человеком; козу нельзя оставлять наидине с капустой или волком..
        /// </summary>
        internal static string start_text {
            get {
                return ResourceManager.GetString("start_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На весь экран.
        /// </summary>
        internal static string win_fullscreen {
            get {
                return ResourceManager.GetString("win_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стиль окна.
        /// </summary>
        internal static string win_style {
            get {
                return ResourceManager.GetString("win_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цель выполнена!
        ///Нажмите ЛКМ, чтобы закрыть программу
        ///Программа будет закрыта через 5 секунд!.
        /// </summary>
        internal static string win_text {
            get {
                return ResourceManager.GetString("win_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В окне.
        /// </summary>
        internal static string win_windowed {
            get {
                return ResourceManager.GetString("win_windowed", resourceCulture);
            }
        }
    }
}
