//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrier.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_EN() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carrier.Resources.lang_EN", typeof(lang_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        internal static string about_name {
            get {
                return ResourceManager.GetString("about_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Carrier program.
        /// </summary>
        internal static string about_name_2 {
            get {
                return ResourceManager.GetString("about_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To continue press left button.
        /// </summary>
        internal static string auto_help {
            get {
                return ResourceManager.GetString("auto_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto.
        /// </summary>
        internal static string auto_name {
            get {
                return ResourceManager.GetString("auto_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In auto mode, the program will
        ///automatically execute the algorithm for solving
        ///the problem of the Carrier. The user can press LMB
        ///to advance the solution of the problem forward or
        ///press LMB to advance the solution of the problem
        ///backward.
        ///
        ///
        ///.
        /// </summary>
        internal static string auto_text {
            get {
                return ResourceManager.GetString("auto_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carry!.
        /// </summary>
        internal static string carrier {
            get {
                return ResourceManager.GetString("carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (C) Fatrahmanov Nikita 2025.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current frame:.
        /// </summary>
        internal static string curr_frame {
            get {
                return ResourceManager.GetString("curr_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source code on Github!.
        /// </summary>
        internal static string github_link {
            get {
                return ResourceManager.GetString("github_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carrier.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string lang_name {
            get {
                return ResourceManager.GetString("lang_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The problem has not been solved!
        ///The conditions were violated!
        ///To start again, click the &quot;Restart&quot; button.
        /// </summary>
        internal static string lose_text {
            get {
                return ResourceManager.GetString("lose_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manual.
        /// </summary>
        internal static string manual_name {
            get {
                return ResourceManager.GetString("manual_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In manual mode, the user will
        ///have to solve the problem of the Carrier himself. 
        ///The user must keep to 
        ///There are certain rules, otherwise he
        ///will lose. Unlike auto mode,
        ///the user needs to move 
        ///the objects need to be clicked on them by the LMB
        ///and click on the &quot;Carry&quot; button..
        /// </summary>
        internal static string manual_text {
            get {
                return ResourceManager.GetString("manual_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        internal static string mode_desc_name {
            get {
                return ResourceManager.GetString("mode_desc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select mode.
        /// </summary>
        internal static string mode_sel {
            get {
                return ResourceManager.GetString("mode_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings_name {
            get {
                return ResourceManager.GetString("settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conditions: it is required to transport a man, a goat, a wolf and a cabbage to the other shore; only two people can be accommodated in the boat; A boat can only sail with a Man; a goat cannot be left alone with a cabbage or a wolf..
        /// </summary>
        internal static string start_text {
            get {
                return ResourceManager.GetString("start_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fullscreen.
        /// </summary>
        internal static string win_fullscreen {
            get {
                return ResourceManager.GetString("win_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Window style.
        /// </summary>
        internal static string win_style {
            get {
                return ResourceManager.GetString("win_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The target is completed!
        ///Click LMB to close the program
        ///The program will be closed in 5 seconds!.
        /// </summary>
        internal static string win_text {
            get {
                return ResourceManager.GetString("win_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windowed.
        /// </summary>
        internal static string win_windowed {
            get {
                return ResourceManager.GetString("win_windowed", resourceCulture);
            }
        }
    }
}
